export const CATALOGO = {
  clavicula_circulos: { nombre: "Movilizacion de clavicula con banda", grupo: "Cuello",
    pasos: ["Banda con ambas manos, algo mas ancha que los hombros.", "Brazos a la altura del pecho, codos algo flexionados.", "Circulos lentos: 10 adelante, 10 atras."],
    sensacion: "Masaje articular suave. El chasquido no molesta si no duele.", errores: "No subas los hombros hacia las orejas.", youtube: "" },
  apertura_pecho_banda: { nombre: "Apertura de pecho con banda", grupo: "Postura",
    pasos: ["Banda con ambas manos, brazos extendidos al frente.", "Sin doblar codos, separa las manos llevando la banda al pecho.", "1 segundo arriba, vuelve controlado."],
    sensacion: "Contraccion entre omoplatos, no en brazos.", errores: "No encojas los hombros.", youtube: "" },
  circulos_hombro_rotacion: { nombre: "Rotacion externa de hombro con banda", grupo: "Hombro",
    pasos: ["Codo pegado al cuerpo, 90 grados, banda en la mano.", "Gira el antebrazo hacia fuera sin mover el codo.", "Vuelve controlado."],
    sensacion: "Activacion en la parte de atras del hombro.", errores: "El codo no se separa del cuerpo.", youtube: "" },
  estiramiento_pectoral_mancuerna: { nombre: "Estiramiento pectoral con mancuerna", grupo: "Postura",
    pasos: ["Tumbado en banco, mancuerna ligera en una mano.", "Deja el brazo colgar fuera del banco.", "Relaja, el peso hace el trabajo. 45s por lado."],
    sensacion: "Estiramiento profundo, sin dolor agudo.", errores: "No uses peso excesivo.", youtube: "" },
  estiramiento_cuello_lateral: { nombre: "Estiramiento de cuello lateral", grupo: "Cuello",
    pasos: ["Inclina la cabeza hacia un hombro sin rotar.", "Mano apoyada suave en la sien, sin tirar.", "30s por lado."],
    sensacion: "Tension suave, nunca dolor ni hormigueo.", errores: "No tires con la mano.", youtube: "" },
  catcow: { nombre: "Cat-cow", grupo: "Columna",
    pasos: ["Cuatro apoyos.", "Inhala arqueando hacia abajo, mirada arriba.", "Exhala redondeando hacia arriba, barbilla al pecho.", "8 repeticiones."],
    sensacion: "Movimiento fluido, sin bloqueos.", errores: "No fuerces el rango.", youtube: "" },
  cossack_squat: { nombre: "Cossack squat", grupo: "Cadera",
    pasos: ["Piernas muy separadas, puntas algo hacia fuera.", "Peso a un lado, flexiona esa rodilla, la otra pierna extendida.", "Talon en el suelo si puedes. Vuelve al centro."],
    sensacion: "Estiramiento en ingle, activacion en gluteo.", errores: "La rodilla no colapsa hacia dentro.", youtube: "" },
  dead_hang: { nombre: "Dead hang activo", grupo: "Hombro",
    pasos: ["Cuelgate de una barra, agarre a la anchura de hombros.", "Deja que el peso descomprima. Sin balanceo.", "20-30 segundos."],
    sensacion: "Traccion suave, nunca dolor punzante.", errores: "Usa apoyo de pies si no aguantas.", youtube: "" },
  estiramiento_dorsal: { nombre: "Estiramiento de dorsal", grupo: "Espalda",
    pasos: ["De rodillas frente a un banco, manos apoyadas.", "Cadera atras, pecho hundido, brazos extendidos.", "Rota levemente a cada lado."],
    sensacion: "Estiramiento largo en el costado.", errores: "No fuerces si molesta la lumbar.", youtube: "" },
  retraccion_escapular: { nombre: "Retraccion escapular", grupo: "Postura",
    pasos: ["Columna neutra.", "Junta los omoplatos atras y abajo.", "3 segundos, inhalando. Suelta al exhalar. 5 veces."],
    sensacion: "Activacion entre omoplatos.", errores: "No arquees la lumbar.", youtube: "" },
  sentadilla_atg: { nombre: "Sentadilla ATG", grupo: "Cadera",
    pasos: ["Pies a la anchura de hombros.", "Baja lo mas profundo posible, talones en el suelo.", "Si se levantan, reduce el rango. Sube controlado."],
    sensacion: "Apertura en cadera y tobillo.", errores: "No sacrifiques los talones por bajar mas.", youtube: "" },
  estiramiento_90_90: { nombre: "Estiramiento 90/90 de cadera", grupo: "Cadera",
    pasos: ["Sentado, una pierna 90 grados delante, otra 90 grados detras.", "Torso erguido, inclinate sobre la de delante.", "45s por lado."],
    sensacion: "Estiramiento en cadera externa e interna.", errores: "No fuerces si hay pinzamiento.", youtube: "" },
  puente_gluteo_resp: { nombre: "Puente de gluteo mas respiracion", grupo: "Cadera",
    pasos: ["Tumbado, rodillas flexionadas.", "Sube la cadera apretando el gluteo.", "5 respiraciones arriba. Baja controlado."],
    sensacion: "Activacion en gluteo, no en lumbar.", errores: "Si trabaja mas la lumbar, baja la altura.", youtube: "" },
  cossack_dinamico: { nombre: "Cossack squat dinamico", grupo: "Running",
    pasos: ["Igual que el Cossack, pero en movimiento continuo.", "Alterna de lado a lado con fluidez."],
    sensacion: "Calentamiento activo de cadera.", errores: "No sacrifiques tecnica por velocidad.", youtube: "" },
  progresivos: { nombre: "Progresivos 15-20s", grupo: "Running",
    pasos: ["Trote muy suave.", "Acelera progresivo en 15-20s hasta el ritmo objetivo.", "Trote suave de vuelta."],
    sensacion: "El cuerpo despierta.", errores: "No aceleres de golpe.", youtube: "" },
  estiramiento_cintilla_it: { nombre: "Estiramiento de cintilla IT", grupo: "Running",
    pasos: ["Cruza la pierna afectada detras de la otra.", "Inclina el torso al lado contrario, sin rotar cadera.", "30s."],
    sensacion: "Estiramiento lateral del muslo.", errores: "No rotes el torso.", youtube: "" },
  foam_roller_gemelo: { nombre: "Foam roller gemelo izquierdo", grupo: "Running",
    pasos: ["Sentado, roller bajo la pantorrilla izquierda.", "Desplaza el peso lento de rodilla a tobillo.", "10-15s en puntos de tension."],
    sensacion: "Presion intensa pero tolerable.", errores: "No ruedes rapido.", youtube: "" },
  circulos_tobillo_ktw: { nombre: "Tobillo mas knee-to-wall", grupo: "Running",
    pasos: ["Circulos de tobillo, 10 por direccion.", "Knee-to-wall: rodilla a la pared, talon en el suelo.", "10 veces por pierna."],
    sensacion: "Mejora progresiva del rango.", errores: "No levantes el talon.", youtube: "" },
  estiramiento_gemelo_soleo: { nombre: "Gemelo/soleo de pie", grupo: "Running",
    pasos: ["Un pie adelante, otro atras, frente a la pared.", "Rodilla trasera extendida = gemelo. Flexionada = soleo.", "30s cada variante, cada pierna."],
    sensacion: "Tension en pantorrilla.", errores: "Talon trasero siempre en el suelo.", youtube: "" },

  // ═══ AVANZADO — RANGO EXTREMO ═══
  split_frontal_progresivo: { nombre: "Split frontal progresivo", grupo: "Avanzado - Rango", avanzado: true,
    pasos: ["Una pierna adelante, otra atras, ambas apoyadas en el suelo (no split completo al inicio).", "Baja la cadera hacia el suelo hasta notar tension, sin dolor agudo.", "Mantén 30-45s. Usa bloques de yoga o cojines bajo las manos si necesitas apoyo.", "Progresa el rango semana a semana, nunca fuerces el salto a split completo."],
    sensacion: "Estiramiento profundo en isquios de la pierna delantera y flexor de cadera de la trasera. Nunca dolor articular en la rodilla.",
    errores: "No relajes la cadera hacia un lado — mantenla cuadrada mirando al frente.", youtube: "" },
  cadera_90_90_dinamico: { nombre: "90/90 dinámico (cambios de lado)", grupo: "Avanzado - Rango", avanzado: true,
    pasos: ["Sentado en 90/90, pasa de un lado a otro rotando por encima de las piernas sin usar las manos.", "Controla el movimiento — no te dejes caer.", "8-10 transiciones completas."],
    sensacion: "Rotación interna y externa de cadera trabajando en conjunto. Al principio cuesta el equilibrio.",
    errores: "No fuerces la transición con las manos — el objetivo es el control activo de cadera.", youtube: "" },
  puente_completo: { nombre: "Puente completo (wheel pose progresivo)", grupo: "Avanzado - Rango", avanzado: true,
    pasos: ["Tumbado, manos junto a las orejas con los dedos hacia los hombros, pies cerca de los glúteos.", "Empuja con manos y pies elevando la cadera y el pecho, extendiendo la columna.", "Si no llegas a la extensión completa, practica el puente de glúteo con extensión de hombro primero.", "Mantén 10-15s, baja controlado."],
    sensacion: "Apertura torácica y de hombro intensa. Progresión lenta y segura, no forzar la columna lumbar.",
    errores: "No hagas esto sin haber calentado bien la columna y los hombros antes.", youtube: "" },
  rueda_abdominal: { nombre: "Rueda abdominal (ab wheel)", grupo: "Avanzado - Control", avanzado: true,
    pasos: ["De rodillas, sujeta la rueda con ambas manos.", "Extiende hacia delante controlando con el core, sin que la lumbar se hunda.", "Vuelve a la posición inicial contrayendo abdomen.", "Empieza con rango parcial, progresa a rango completo."],
    sensacion: "Tensión intensa en todo el core, especialmente recto abdominal y oblicuos.",
    errores: "Si la zona lumbar se arquea o duele, reduce el rango inmediatamente.", youtube: "" },
  puente_hombro_extendido: { nombre: "Puente de glúteo con extensión de hombro", grupo: "Avanzado - Rango", avanzado: true,
    pasos: ["Tumbado, rodillas flexionadas, brazos extendidos por encima de la cabeza en el suelo.", "Eleva la cadera mientras mantienes los brazos extendidos y pegados al suelo.", "5 respiraciones arriba."],
    sensacion: "Combina activación de glúteo con apertura de hombro — preparación para el puente completo.",
    errores: "Si los brazos se despegan del suelo, reduce el rango de la cadera.", youtube: "" },
  mariposa_profunda: { nombre: "Mariposa profunda (butterfly stretch)", grupo: "Avanzado - Rango", avanzado: true,
    pasos: ["Sentado, plantas de los pies juntas, rodillas hacia fuera.", "Inclínate hacia delante desde la cadera, espalda recta, no redondeada.", "Mantén 45-60s, respira profundo."],
    sensacion: "Estiramiento en ingle y cadera interna. Progresa acercando los talones al cuerpo con el tiempo.",
    errores: "No redondees la espalda para bajar más — el movimiento viene de la cadera.", youtube: "" },
  split_lateral_progresivo: { nombre: "Split lateral progresivo", grupo: "Avanzado - Rango", avanzado: true,
    pasos: ["Piernas muy separadas, pies apuntando al frente.", "Desplaza la cadera hacia atrás y abajo manteniendo las piernas rectas.", "Apóyate en las manos o antebrazos según el rango.", "Mantén 30-45s, progresa el ancho gradualmente."],
    sensacion: "Estiramiento intenso en aductores. Requiere semanas de trabajo constante para progresar con seguridad.",
    errores: "Nunca fuerces el rango de golpe — el split lateral es de progresión lenta.", youtube: "" },

  // ═══ AVANZADO — POTENCIA Y CONTROL ═══
  skips_altos: { nombre: "Skips altos (A-skips)", grupo: "Avanzado - Potencia", avanzado: true,
    pasos: ["Trote en el sitio o avanzando, llevando la rodilla arriba con fuerza en cada paso.", "Brazos activos, coordinados con las piernas.", "20-30m o 20-30 segundos, 3-4 series."],
    sensacion: "Activación potente de flexores de cadera, ritmo cardíaco sube rápido.",
    errores: "No pierdas la postura vertical del torso al llevar la rodilla arriba.", youtube: "" },
  skips_laterales: { nombre: "Skips laterales", grupo: "Avanzado - Potencia", avanzado: true,
    pasos: ["Desplazamiento lateral con elevación de rodilla cruzada, tipo carioca controlado.", "Mantén el core activo y la cadera estable.", "15-20m por lado, 2-3 series."],
    sensacion: "Trabajo de estabilidad lateral de cadera y coordinación.",
    errores: "No dejes que la cadera rote en exceso — control ante todo.", youtube: "" },
  bounds_horizontales: { nombre: "Bounds horizontales (saltos de zancada)", grupo: "Avanzado - Potencia", avanzado: true,
    pasos: ["Desde parado, salta hacia delante con una pierna, aterrizando con la contraria en zancada amplia.", "Alterna piernas en cada salto, buscando distancia y control en el aterrizaje.", "6-8 bounds por serie, 2-3 series."],
    sensacion: "Potencia explosiva de cadera y pierna. Es exigente — requiere buena base antes de introducirlo.",
    errores: "El aterrizaje debe ser controlado, no un choque duro. Si duele la rodilla, para inmediatamente.", youtube: "" },
  saltos_laterales_control: { nombre: "Saltos laterales con control (lateral bounds)", grupo: "Avanzado - Potencia", avanzado: true,
    pasos: ["Salta lateralmente de una pierna a la otra, aterrizando y estabilizando 1-2 segundos antes del siguiente salto.", "Rodilla alineada con el pie en cada aterrizaje.", "6-8 saltos por lado, 2-3 series."],
    sensacion: "Control excéntrico de rodilla y tobillo — clave para prevenir lesiones en cambios de dirección.",
    errores: "Si la rodilla colapsa hacia dentro al aterrizar, reduce la velocidad y la distancia.", youtube: "" },
  step_ups_explosivos: { nombre: "Step-ups explosivos", grupo: "Avanzado - Potencia", avanzado: true,
    pasos: ["Sobre un banco o step, sube con una pierna generando la máxima potencia posible.", "Puedes despegar el pie de apoyo del suelo brevemente en la parte alta.", "6-8 reps por pierna, controlando el descenso."],
    sensacion: "Potencia unilateral de pierna, transferible directamente a la zancada de sprint.",
    errores: "Usa una altura de banco que permitas controlar — no comprometas la técnica por la altura.", youtube: "" },
  giros_rusos_medicine_ball: { nombre: "Giros rusos con balón medicinal", grupo: "Avanzado - Control", avanzado: true,
    pasos: ["Sentado con el torso inclinado hacia atrás 45º, pies elevados o apoyados según nivel.", "Rota el torso de lado a lado tocando el suelo con el balón a cada lado.", "12-16 repeticiones totales (6-8 por lado)."],
    sensacion: "Activación intensa de oblicuos y core rotacional.",
    errores: "El movimiento viene del torso, no solo de los brazos.", youtube: "" },
  animal_flow_bear_crawl: { nombre: "Bear crawl (animal flow)", grupo: "Avanzado - Control", avanzado: true,
    pasos: ["En cuadrupedia con rodillas ligeramente elevadas del suelo.", "Avanza moviendo mano y pie contrario a la vez, manteniendo la cadera baja y estable.", "10-15m, 2-3 series."],
    sensacion: "Control de core y hombro bajo carga dinámica, coordinación cruzada.",
    errores: "No dejes que la cadera suba demasiado — mantenla a la altura de los hombros.", youtube: "" },
  saltos_profundidad_suave: { nombre: "Saltos en profundidad suave (drop jumps ligeros)", grupo: "Avanzado - Potencia", avanzado: true,
    pasos: ["Desde un step bajo (15-20cm), baja y aterriza con ambos pies, absorbiendo con las rodillas.", "Inmediatamente después, salto vertical corto hacia arriba.", "4-6 repeticiones, solo con buena técnica de aterrizaje ya dominada."],
    sensacion: "Trabajo de rigidez elástica del tobillo y control de aterrizaje — avanzado, introducir con cautela.",
    errores: "Solo progresar aquí si los saltos laterales y bounds ya se dominan sin molestia articular.", youtube: "" },
  rotacion_toracica_cuadrupedia: { nombre: "Rotación torácica en cuadrupedia (thread the needle)", grupo: "Avanzado - Rango", avanzado: true,
    pasos: ["En cuadrupedia, pasa un brazo por debajo del cuerpo rotando el torso, apoyando el hombro y la cabeza en el suelo.", "Vuelve rotando hacia arriba, llevando el mismo brazo hacia el techo.", "6-8 repeticiones por lado, movimiento fluido."],
    sensacion: "Movilidad torácica y de hombro combinadas, mejora la rotación en la zancada de sprint.",
    errores: "Mantén la cadera estable — la rotación es solo del torso hacia arriba.", youtube: "" },
  // ═══ FUERZA — PECHO ═══
  press_inclinado_maquina: { nombre: "Press inclinado con mancuernas", grupo: "Pecho", categoria: "fuerza",
    pasos: ["Ajusta el banco a unos 30-45 grados de inclinación.", "Siéntate con una mancuerna en cada mano apoyadas en los muslos, y túmbate impulsándolas hasta la altura del pecho.", "Espalda apoyada, escápulas juntas, pies firmes en el suelo.", "Empuja hacia arriba y ligeramente hacia dentro sin llegar a chocar las mancuernas ni bloquear del todo el codo.", "Baja controlado hasta que las manos queden a la altura del pecho superior, sintiendo estiramiento sin forzar el hombro."],
    sensacion: "Tensión en la parte superior del pecho y algo de hombro anterior. No debe doler en el hombro.",
    errores: "No arquees excesivamente la espalda baja para empujar más peso. Si el banco está a más de 45 grados, el hombro se lleva casi todo el trabajo.", youtube: "" },
  press_plano_maquina_discos: { nombre: "Press banca con barra", grupo: "Pecho", categoria: "fuerza",
    pasos: ["Túmbate en el banco plano con los ojos justo debajo de la barra.", "Agarre algo más ancho que los hombros, escápulas juntas y apretadas contra el banco, pies firmes en el suelo.", "Saca la barra del soporte y llévala sobre la línea del pecho medio.", "Baja controlado hasta rozar el pecho, con los codos a unos 45 grados del torso (no abiertos del todo).", "Empuja hacia arriba en línea ligeramente diagonal hacia los hombros, sin bloquear el codo de golpe."],
    sensacion: "Tensión uniforme en todo el pecho, con tríceps y hombro asistiendo. Al ser peso libre, notarás más trabajo de estabilización que en máquina.",
    errores: "No rebotes la barra en el pecho ni despegues los glúteos del banco. Si entrenas solo y vas al límite, usa los soportes de seguridad.", youtube: "" },
  pec_fly_maquina: { nombre: "Aperturas con mancuernas en banco", grupo: "Pecho", categoria: "fuerza",
    pasos: ["Túmbate en el banco plano (o ligeramente inclinado) con una mancuerna en cada mano.", "Brazos extendidos sobre el pecho con una flexión ligera y FIJA en el codo — esa flexión no cambia en todo el movimiento.", "Abre los brazos en arco hacia los lados, bajando hasta sentir estiramiento en el pecho, sin que los codos bajen por debajo de la línea del banco.", "Cierra en el mismo arco contrayendo el pecho, sin que las mancuernas lleguen a chocar arriba."],
    sensacion: "Estiramiento y contracción centrados en el pecho, sin apenas trabajo de brazo.",
    errores: "No conviertas el movimiento en un press flexionando y extendiendo el codo. Usa menos peso del que crees — este ejercicio castiga el hombro si te pasas.", youtube: "" },

  // ═══ FUERZA — HOMBRO ═══
  elevaciones_laterales_polea_cruzada: { nombre: "Elevaciones laterales polea muñequera cruzadas", grupo: "Hombro", categoria: "fuerza",
    pasos: ["Polea baja, muñequera cruzada por delante del cuerpo hacia el lado contrario.", "Eleva el brazo lateralmente hasta la altura del hombro.", "Baja controlado sin dejar que el peso caiga de golpe."],
    sensacion: "Tensión constante en el hombro lateral durante todo el recorrido, incluso al inicio del movimiento — a diferencia de la mancuerna.",
    errores: "No uses impulso del cuerpo para levantar el brazo.", youtube: "" },
  elevaciones_laterales_mancuerna: { nombre: "Elevaciones laterales mancuerna", grupo: "Hombro", categoria: "fuerza",
    pasos: ["De pie, mancuernas a los lados, ligera flexión de codo.", "Eleva los brazos lateralmente hasta la altura del hombro.", "Baja controlado, sin dejar caer el peso."],
    sensacion: "Quemazón en la parte lateral del hombro al final de la serie. El primer tramo del movimiento es el más difícil.",
    errores: "No encojas los trapecios — el movimiento es del hombro, no del cuello.", youtube: "" },
  elevaciones_frontales_unilateral: { nombre: "Elevaciones frontales unilateral", grupo: "Hombro", categoria: "fuerza",
    pasos: ["De pie, mancuerna en una mano, brazo relajado al frente del cuerpo.", "Eleva el brazo recto al frente hasta la altura del hombro.", "Baja controlado, cambia de brazo tras completar las reps."],
    sensacion: "Tensión en la parte delantera del hombro. Aislado, un brazo a la vez para mantener control estricto.",
    errores: "No balancees el torso hacia atrás para ayudarte a subir el peso.", youtube: "" },

  // ═══ FUERZA — TRÍCEPS ═══
  extension_katana_polea_baja: { nombre: "Extension katana en polea baja", grupo: "Triceps", categoria: "fuerza",
    pasos: ["Polea baja, agarre de cuerda o barra, de espaldas a la máquina.", "Extiende el brazo hacia arriba y adelante, como desenvainando una katana.", "Vuelve controlado."],
    sensacion: "Estiramiento y contracción intensos en la cabeza larga del tríceps, distinto al press habitual.",
    errores: "Mantén el codo fijo cerca de la cabeza, no lo dejes caer hacia el cuerpo.", youtube: "" },
  extension_polea_alta_v: { nombre: "Extension polea alta agarre en V", grupo: "Triceps", categoria: "fuerza",
    pasos: ["Polea alta, agarre en V, codos pegados al cuerpo.", "Extiende los brazos hacia abajo sin mover los codos de sitio.", "Vuelve controlado hasta 90 grados aproximadamente."],
    sensacion: "Tensión limpia en todo el tríceps, especialmente al bloquear abajo.",
    errores: "No dejes que los codos se separen del cuerpo durante el movimiento.", youtube: "" },
  press_frances_mancuernas: { nombre: "Press frances con mancuernas", grupo: "Triceps", categoria: "fuerza",
    pasos: ["Tumbado o sentado, mancuernas por encima de la cabeza, brazos extendidos.", "Flexiona los codos bajando el peso detrás de la cabeza.", "Extiende de vuelta sin mover los hombros."],
    sensacion: "Estiramiento profundo del tríceps al bajar, especialmente la cabeza larga.",
    errores: "No abras los codos hacia fuera — deben apuntar al frente durante todo el recorrido.", youtube: "" },

  // ═══ FUERZA — ESPALDA ═══
  dominadas: { nombre: "Dominadas", grupo: "Espalda", categoria: "fuerza",
    pasos: ["Agarre prono (palmas hacia fuera), manos algo más anchas que los hombros.", "Cuelga con los brazos extendidos, escápulas activas (no colgando pasivo).", "Tira hasta que la barbilla supere la barra, sin balanceo ni impulso de piernas.", "Baja controlado hasta extensión completa antes de la siguiente repetición."],
    sensacion: "Activación de dorsal y bíceps. Al final de la serie, quemazón en dorsal — no debe doler el hombro.",
    errores: "No hagas kipping (balanceo con las piernas) para ayudarte — cada repetición debe ser limpia.", youtube: "" },
  jalon_pecho_unilateral: { nombre: "Jalon al pecho unilateral", grupo: "Espalda", categoria: "fuerza",
    pasos: ["Sentado en la polea alta, agarre unilateral con una mano.", "Tira hacia abajo llevando el codo hacia la cadera.", "Vuelve controlado sin perder la tensión de la espalda."],
    sensacion: "Contracción marcada en el dorsal de ese lado, permite corregir desequilibrios entre lados.",
    errores: "No uses el impulso del torso hacia atrás para tirar del peso.", youtube: "" },
  remo_en_t: { nombre: "Remo con barra", grupo: "Espalda", categoria: "fuerza",
    pasos: ["De pie, barra en el suelo, pies a la anchura de caderas.", "Bisagra de cadera: empuja el culo atrás con la espalda recta hasta que el torso quede a unos 45 grados (o más horizontal si controlas la técnica).", "Agarre prono algo más ancho que los hombros, brazos colgando.", "Tira la barra hacia el ombligo llevando los codos hacia atrás y juntando las escápulas.", "Baja controlado hasta extender los brazos, sin dejar que la espalda se redondee ni el torso suba."],
    sensacion: "Contracción intensa en la espalda media, entre los omóplatos, con dorsal trabajando en el tirón.",
    errores: "No conviertas el movimiento en un balanceo de torso — si tienes que impulsarte con la espalda, baja el peso. Cuello neutro, no levantes la cabeza para mirar al frente.", youtube: "" },
  remo_unilateral_polea: { nombre: "Remo unilateral en polea", grupo: "Espalda", categoria: "fuerza",
    pasos: ["Polea baja, agarre unilateral, ligera flexión de rodillas.", "Tira hacia la cadera llevando el codo atrás, gira ligeramente el torso.", "Vuelve controlado sin perder la postura."],
    sensacion: "Trabajo completo de espalda media y dorsal, con algo de rotación de torso controlada.",
    errores: "No rotes en exceso el torso — la rotación debe ser sutil, no el motor del movimiento.", youtube: "" },
  pullover_polea: { nombre: "Pullover en polea", grupo: "Espalda", categoria: "fuerza",
    pasos: ["Polea alta, agarre con barra o cuerda, brazos extendidos por encima de la cabeza.", "Baja los brazos en arco hasta la altura del muslo, codos con ligera flexión fija.", "Vuelve controlado arriba."],
    sensacion: "Estiramiento amplio del dorsal, distinto a los ejercicios de tirón horizontal.",
    errores: "No flexiones y extiendas el codo durante el movimiento — debe permanecer fijo.", youtube: "" },

  // ═══ FUERZA — BÍCEPS ═══
  curl_bayesian_polea: { nombre: "Curl bayesian en polea", grupo: "Biceps", categoria: "fuerza",
    pasos: ["De pie, de espaldas a la polea baja, brazo detrás del cuerpo.", "Flexiona el codo llevando la mano hacia el hombro.", "Baja controlado sintiendo el estiramiento detrás."],
    sensacion: "Estiramiento del bíceps en una posición poco habitual — muy efectivo para la cabeza larga.",
    errores: "No balancees el cuerpo hacia delante para ayudarte.", youtube: "" },
  curl_bilateral_mancuernas: { nombre: "Curl bilateral con mancuernas", grupo: "Biceps", categoria: "fuerza",
    pasos: ["De pie, mancuernas a los lados, palmas hacia delante.", "Flexiona ambos codos llevando el peso hacia el hombro.", "Baja controlado sin balancear el torso."],
    sensacion: "Contracción clásica del bíceps, sencilla de sentir y controlar.",
    errores: "No uses impulso de cadera o espalda para levantar el peso.", youtube: "" },
  curl_maquina_scott: { nombre: "Curl concentrado con mancuerna", grupo: "Biceps", categoria: "fuerza",
    pasos: ["Siéntate en el banco con las piernas abiertas, mancuerna en una mano.", "Apoya la parte de atrás del brazo (tríceps) contra la cara interna del muslo del mismo lado — ese apoyo es lo que impide que hagas trampa.", "Con el brazo colgando y extendido, flexiona el codo llevando la mancuerna hacia el hombro.", "Aprieta 1 segundo arriba y baja controlado hasta extender del todo, sin soltar la tensión.", "Completa todas las repeticiones de un brazo antes de cambiar."],
    sensacion: "Aislamiento total del bíceps, sin poder ayudarte con el cuerpo — quemazón intensa al final de la serie.",
    errores: "No despegues el brazo del muslo para ayudarte, ni dejes caer el peso de golpe en la bajada — la fase excéntrica controlada es donde está gran parte del estímulo.", youtube: "" },

  // ═══ FUERZA — PIERNA ═══
  cossack_squat_peso_corporal: { nombre: "Cossack squat con peso corporal", grupo: "Pierna", categoria: "fuerza",
    pasos: ["Piernas muy separadas, puntas ligeramente hacia fuera.", "Lleva el peso a un lado flexionando esa rodilla, la otra pierna extendida.", "Vuelve al centro y repite al otro lado."],
    sensacion: "Estiramiento en la ingle de la pierna extendida, activación en glúteo de la pierna flexionada.",
    errores: "Mantén el talón de la pierna flexionada en el suelo si el rango lo permite.", youtube: "" },
  sentadilla_atg_sin_peso: { nombre: "Sentadilla ATG sin peso", grupo: "Pierna", categoria: "fuerza",
    pasos: ["Pies a la anchura de hombros.", "Baja lo más profundo posible manteniendo los talones en el suelo.", "Sube controlado sin perder la posición de la espalda."],
    sensacion: "Apertura de cadera y tobillo. Trabajo de rango completo más que de carga.",
    errores: "No sacrifiques la posición de los talones por bajar más — reduce el rango si hace falta.", youtube: "" },
  peso_muerto_rumano: { nombre: "Peso muerto rumano", grupo: "Pierna", categoria: "fuerza",
    pasos: ["De pie, barra o mancuernas al frente de los muslos.", "Empuja la cadera hacia atrás manteniendo la espalda recta, baja el peso pegado a las piernas.", "Sube empujando con los isquios y el glúteo, sin redondear la espalda."],
    sensacion: "Estiramiento intenso en isquiotibiales al bajar, activación de glúteo al subir.",
    errores: "No redondees la zona lumbar en ningún punto del recorrido.", youtube: "" },

  // ═══ FUERZA — CADERA / GLÚTEO ═══
  puente_gluteo_abduccion: { nombre: "Puente gluteo + abduccion", grupo: "Cadera", categoria: "fuerza",
    pasos: ["Tumbado, rodillas flexionadas, banda elástica por encima de las rodillas.", "Eleva la cadera apretando el glúteo.", "Arriba, separa las rodillas contra la banda y vuelve a juntarlas antes de bajar."],
    sensacion: "Activación combinada de glúteo mayor y medio.",
    errores: "No dejes que la lumbar cargue el movimiento — el impulso viene del glúteo.", youtube: "" },
  clamshells_banda: { nombre: "Clamshells con banda", grupo: "Cadera", categoria: "fuerza",
    pasos: ["Tumbado de lado, rodillas flexionadas, banda por encima de las rodillas.", "Abre la rodilla superior como una almeja, sin mover la cadera.", "Cierra controlado."],
    sensacion: "Activación aislada del glúteo medio — clave para la estabilidad de cadera en la carrera.",
    errores: "No rotes la cadera hacia atrás para abrir más la rodilla.", youtube: "" },

  // ═══ FUERZA — CORE ═══
  plancha_frontal: { nombre: "Plancha frontal", grupo: "Core", categoria: "fuerza",
    pasos: ["Antebrazos en el suelo, codos bajo los hombros.", "Cuerpo en línea recta de cabeza a talones, abdomen y glúteo activados.", "Mantén la posición respirando con normalidad."],
    sensacion: "Tensión constante en todo el core, sin dolor lumbar.",
    errores: "No dejes que la cadera caiga ni que suba en exceso — busca la línea recta.", youtube: "" },
  plancha_lateral: { nombre: "Plancha lateral", grupo: "Core", categoria: "fuerza",
    pasos: ["Apoyo en un antebrazo, cuerpo de lado en línea recta.", "Cadera elevada, no apoyada en el suelo.", "Mantén la posición, cambia de lado."],
    sensacion: "Activación intensa de oblicuos del lado que trabaja.",
    errores: "No dejes que la cadera caiga hacia el suelo durante la serie.", youtube: "" },
  plancha_frontal_lateral: { nombre: "Plancha frontal + lateral", grupo: "Core", categoria: "fuerza",
    pasos: ["Combina plancha frontal y plancha lateral a cada lado en la misma serie.", "Reparte el tiempo total entre las tres posiciones.", "Mantén la respiración constante en cada tramo."],
    sensacion: "Trabajo completo del core desde varios ángulos en una sola serie.",
    errores: "No sacrifiques la técnica de una posición por acabar antes — mejor menos tiempo con buena forma.", youtube: "" },
};
